ls:
  packages:
    .dir: kebab-case
    .ts: kebab-case
    .tsx: kebab-case
    .js: kebab-case
    .d.ts: kebab-case
    .html: kebab-case
    .scss: kebab-case
    .spec.ts: kebab-case | kebab-case
    .config.js: kebab-case

ignore:
  - .git
  - .bin
  - packages/**/node_modules
