[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/",
    "public/"
]

[type.images]
extend-glob = ["*.png", "*.jpg", "*.jpeg", "*.bmp"]
check-file = false

[type.vectors]
extend-glob = ["*.svg"]
check-file = false

[type.fonts]
extend-glob = ["*.ttf", "*.eot", "*.otf", "*.woff"]
check-file = false

[type.documents]
extend-glob = ["*.pdf", "*.docx", "*.rtf", "*.xlsx"]
check-file = false
