# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: true

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [15.x]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upgrade npm to v7
        run: |
          npm i -g npm@7 lerna
      - name: Lerna configure
        run: |
          npx lerna bootstrap
          npx lerna link

      - name: Install
        run: |
          npm install
      - name: Lint code
        run: |
          npm run lint
